name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          git config --global user.email "956341817@qq.com"
          git config --global user.name "wentian"
      - uses: actions/setup-node@v1
        with:
          node-version: 12 
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install
          npm run build
          npm version patch
          npm publish
    env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
