name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          npm config set registry https://registry.npm.taobao.org
          npm install -g yarn
          yarn add husky pre-commit lint-staged @commitlint/cli @commitlint/config-conventional -D
          npm install
          npm version patch
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
