name: Node.js Package

on:
  pull_request:
    branches:
      - master
    paths:
        src/*
  push:
    branches:
      - master 
    paths:
        src/*


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          npm install
          npm version patch
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
